name: Run ASIM testers on "eco-connector-test" workspace
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, labeled]
    paths:
    - 'Parsers/ASimDns/Parsers/**'
    - 'Parsers/ASimNetworkSession/Parsers/**'
    - 'Parsers/ASimWebSession/Parsers/**'
    - 'Parsers/ASimProcessEvent/Parsers/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  runAsimTesters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false
          fetch-depth: 0
      - name: Run Asim testers
        shell: pwsh
        run: |
          & ".script/tests/asimParsersTest/runAsimTesters.ps1"
